import DivApp from './components/modules/main/DivApp'
import './globals.css'

export const metadata = {
  title: 'TikTok Coins: Buy and recharge Coins to send Gift | Tiktok',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-full min-h-full overflow-hidden">
        <DivApp />
        {children}
      </body>
    </html>
  )
}
